---
ID: "6f33771e-bc48-4c5a-aa03-947b6bed856a"
Parent: "37f44d51-8862-4029-a0c1-acd0f3ea357b"
Template: "37f44d51-8862-4029-a0c1-acd0f3ea357b"
Path: /sitecore/templates/Foundation/Theming/ParametersTemplate_HasContainerWithBackgroundAndAlignment/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190730T125942Z
