---
ID: "373393a6-aa10-4771-b9c2-2ea1eb0583f5"
Parent: "bdbc3890-5204-46ba-a0de-8df7d21aed78"
Template: "3a45a723-64ee-4919-9d41-02fd40fd1466"
Path: /sitecore/layout/Layouts/Project/Eurolife/Default
DB: master
SharedFields:
- ID: "a036b2bc-ba04-44f6-a75f-bae6cd242abf"
  Hint: Path
  Value: /Views/Website/Layouts/Layout.cshtml
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190508T054012Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
