---
ID: "0af507da-6c4e-448e-a66a-52afb6dde05f"
Parent: "f6037853-17bc-43e1-9e3a-b9ef0e835979"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/Forms/template-contact/Page/Section/SubSection/Form Item/Settings"
DB: master
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191024T143557Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
