---
ID: "39b67c64-2fbc-4860-95e7-c3b7accee0b3"
Parent: "2a9f943d-6a09-43dc-9917-fc5552aac173"
Template: "2a9f943d-6a09-43dc-9917-fc5552aac173"
Path: /sitecore/templates/Project/Common/Content Types/Blog/Blog Articles Slider/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210127T133813Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
