---
ID: "48a8f570-a8c2-443f-a5b9-e1abe4fd3a9f"
Parent: "e0d8e718-868c-486b-97b8-00901addf08d"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/ContactFormGrtemplate/Page/Section/SubSection/Form Item/Settings
DB: master
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190930T200028Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
