---
ID: "1278787e-bf05-4aed-9596-fad008122c04"
Parent: "cc320b86-c936-4da1-a816-f723192ff7a8"
Template: "cc320b86-c936-4da1-a816-f723192ff7a8"
Path: /sitecore/templates/Project/Eurolife/Page Types/Blog/Products List/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{70DBEA9E-F842-4F79-A111-DD9D803526EE}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200122T091026Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
