---
ID: "8486e910-af9d-49f2-880c-70bf8e39b996"
Parent: "f39c5c0e-3ef9-4626-843f-5d439658fdb5"
Template: "b2613cc1-a748-46a3-a0db-3774574bd339"
Path: /sitecore/templates/Branches/Foundation/Multisite/RenderingSettings
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: apps/16x16/routes.png
- ID: "854cc8f6-94ad-4521-a4b6-44ed8f794c98"
  Hint: Command
  Value: "multisite:createdatasourcesetting(parentID=$ParentID)"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{3E3F4A4D-CE26-42FC-9AC0-F1011CB198ED}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190521T112503Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
