---
ID: "c8e74bef-5ec6-451b-953c-868559f9f146"
Parent: "bc2e9e3c-e8bc-4ebd-a5b9-f5ce7b36685d"
Template: "fe52759a-2ce3-4a73-9cff-ce38a089ce8d"
Path: /sitecore/content/Eurolife/Global/Dictionary/Product
DB: master
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191029T092903Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190529T093429Z
