---
ID: "6a27af09-a74a-4442-8aa2-967f9fa12498"
Parent: "f634b944-bc21-4ea6-bd97-c00d5eb28b59"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/Forms/omadiki-asfalisi-affinities/Page/Section/SubSection/Radio Button List/Settings"
DB: master
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191113T141835Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
