---
ID: "6ac77ad4-e1a2-4664-b76f-7e7c27fae05a"
Parent: "d886dd20-b9a7-46f8-8808-07bbe0ff5e58"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/Forms/askisi-dikaiomaton/Page/Section/SubSection/Dropdown List/Settings"
DB: master
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191024T142652Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
