---
ID: "98840516-9993-49a2-afb1-bdcf9562822a"
Parent: "dae20e3b-e13c-4087-8aea-3a016e521d54"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Feature/Panels/Product Panels Group
DB: master
SharedFields:
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: CreateProductPanelsGroup
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Wedia.Feature.Panels.Controllers.PanelsController, Wedia.Feature.Panels
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190606T094530Z
    - ID: "77593ad2-0761-4d3e-8e17-82a304029640"
      Hint: Supports Local Datasource
      Type: Checkbox
      Value: 1
