---
ID: "30aebea1-0b46-4ac4-8f58-45ae30dc1a89"
Parent: "4bba5378-b7e4-493a-8ce1-58a75da05707"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Complaint Form/Page/Section/SubSection/Radio Button List/Settings
DB: master
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191031T161536Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
