---
ID: "3cff7bfc-9802-48b4-97ec-34fcab2b2fff"
Parent: "dc8aefa5-e96f-4ebb-93b7-1aa9a5dc8155"
Template: "dc8aefa5-e96f-4ebb-93b7-1aa9a5dc8155"
Path: /sitecore/templates/Project/Eurolife/Page Types/Jobs/Job/__Standard Values
DB: master
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200214T114900Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
