---
ID: "4d4e741f-c5d2-4655-854b-6324000230cc"
Parent: "548c64c6-f5e0-495e-847e-9d6aa78962e6"
Template: "548c64c6-f5e0-495e-847e-9d6aa78962e6"
Path: /sitecore/templates/Project/Common/Content Types/EurolifeCalculatorTool/Target Group/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201221T082432Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
