---
ID: "7f400ffc-4b09-4138-8eab-6d638fd1c80d"
Parent: "025fd265-8edf-497d-a2e0-afb0f8b89332"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/vickyTestForm/Page/00N0E000007hClD/Settings
DB: master
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200529T085127Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
