---
ID: "e7a33336-ca96-46d2-b4b2-e59cff4c2238"
Parent: "8ded5be5-8cf5-4d9c-ac6f-b28c797ca805"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Feature/Media/_HasMediaUrl/Action
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190820T142835Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
