---
ID: "1d72831b-d235-4be6-90bf-c7c432f7e37d"
Parent: "13d8b255-915e-47ad-9076-b9e41b68853f"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/Forms/askisi-dikaiomaton/Page/Section/SubSection/Radio Button List personal data/Settings"
DB: master
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191031T154954Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
