---
ID: "c285bc8c-28df-40ee-99ae-01e71ec2ce56"
Parent: "ae8b3fd1-cd52-49c5-9cfd-fde8b7d58751"
Template: "ae8b3fd1-cd52-49c5-9cfd-fde8b7d58751"
Path: /sitecore/templates/Feature/PageContent/_HasPageImageContent/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190510T073313Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
