---
ID: "2ebd3150-e194-48f6-8aa9-c0d358d77a16"
Parent: "f9be04cf-b18a-4cf7-9a9f-f757a73e44c1"
Template: "f9be04cf-b18a-4cf7-9a9f-f757a73e44c1"
Path: /sitecore/templates/Project/Common/Content Types/Panels/Panel Item/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190528T114439Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
