---
ID: "14b87cec-1689-40da-b410-5e8bfc976118"
Parent: "7753c4b8-ffb7-4ef8-8f62-85a28ae89e2c"
Template: "7753c4b8-ffb7-4ef8-8f62-85a28ae89e2c"
Path: /sitecore/templates/Project/Common/Content Types/Highlights/Highlights Group/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190527T133526Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
