---
ID: "7ceb6b51-0a6a-4eac-80a3-80df1cc877b9"
Parent: "7eb13c04-c293-4619-aab2-4456140eaaf7"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/Forms/askisi-dikaiomaton/Page/Section/SubSection/Radio Button List/Settings"
DB: master
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191024T142449Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
