---
ID: "d7852ddc-b13d-400a-beb6-eb2c79a4ab38"
Parent: "a4d6cf4d-cb60-4a24-83c3-94cd3dc54815"
Template: "a4d6cf4d-cb60-4a24-83c3-94cd3dc54815"
Path: /sitecore/templates/Foundation/Theming/ParametersTemplate_FixedHeight/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190524T145920Z
    - ID: "43df3ad6-57ec-448f-9cf5-a66da1e4debe"
      Hint: Fixed height
      Type: Checkbox
      Value: 1
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
