---
ID: "1fa9a0fc-32d8-499e-aae5-843b07e01e04"
Parent: "2bb88d51-eae0-4aa1-ac42-d14ab7f3d866"
Template: "62b2fb1b-fd79-403a-aed2-9d1f464a2e63"
Path: /sitecore/content/Eurolife/Global/Teasers/Products oxima Why Choose Us
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 800
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "015650f6-49a4-401c-b484-b9410a78c8ca"
      Hint: TeaserSummary
      Value: rdgdrgdr
    - ID: "1c2f6ebb-7eb9-47f8-af61-57f1174108fe"
      Hint: TeaserTitle
      Value: drgrdgdr
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190808T150100Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "015650f6-49a4-401c-b484-b9410a78c8ca"
      Hint: TeaserSummary
      Value: |
        &Phi;&rho;&omicron;&nu;&tau;ί&zeta;&omicron;&upsilon;&mu;&epsilon; ώ&sigma;&tau;&epsilon; &eta; &pi;&rho;&omicron;&sigma;&tau;&alpha;&sigma;ί&alpha; &alpha;&upsilon;&tau;ώ&nu; &pi;&omicron;&upsilon; έ&chi;&omicron;&upsilon;&nu; &alpha;&xi;ί&alpha; &gamma;&iota;&alpha; &epsilon;&sigma;ά&sigmaf;
        &nu;&alpha; &epsilon;ί&nu;&alpha;&iota; &mu;&iota;&alpha; &epsilon;&pi;έ&nu;&delta;&upsilon;&sigma;&eta; &pi;&omicron;&upsilon; &alpha;&pi;&omicron;&delta;ί&delta;&epsilon;&iota;
    - ID: "1c2f6ebb-7eb9-47f8-af61-57f1174108fe"
      Hint: TeaserTitle
      Value: Γιατί να μας επιλέξετε
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190604T125716Z
    - ID: "af8b8e9d-3fe1-4bff-9062-4a139d8f4975"
      Hint: TeaserCTA
      Value: 
