---
ID: "67f03613-b947-47b7-bf3c-17d90ead181b"
Parent: "e4518440-eb6e-4ef0-8889-fc9e92dac933"
Template: "e4518440-eb6e-4ef0-8889-fc9e92dac933"
Path: /sitecore/templates/Project/Common/Content Types/EurolifeCalculatorTool/Bundle/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201214T153721Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
