---
ID: "4c99de95-39a6-4188-b1b6-7ce2c2673112"
Parent: "1bd8973a-c133-4bcb-87a3-d4ef07b7f098"
Template: "1bd8973a-c133-4bcb-87a3-d4ef07b7f098"
Path: /sitecore/templates/Project/Common/Content Types/FAQ/FAQ Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{CA06FBA2-CC7D-48EC-919F-6CCC4D0957CC}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190520T125911Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
