---
ID: "d9c01173-d838-4618-9054-e114d4d68f26"
Parent: "281383db-c1d6-4557-b5ef-3163f9dfe725"
Template: "00d32287-3ed5-4d97-9b00-0f8ef05f6db8"
Path: /sitecore/content/Eurolife/Global/Links/Main Menu/Products Menu
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: "-200"
Languages:
- Language: "el-GR"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210126T161606Z
    - ID: "428f3a15-002b-4ebb-a9b5-cc021d99f648"
      Hint: NavigationRootTitle
      Value: Τα προγράμματά μας
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
